# Generated by Django 2.0.5 on 2018-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
