# Generated by Django 2.0.1 on 2018-05-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180508_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
