# Generated by Django 2.0.1 on 2018-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180511_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='signature',
            field=models.TextField(default='', help_text='Paste security signature of command.'),
        ),
    ]
