# Generated by Django 2.0.1 on 2018-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_job_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cmd_list',
            field=models.TextField(help_text='Command separated list of command and parameters.'),
        ),
    ]
