# Generated by Django 3.1.5 on 2021-01-31 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_auto_20180513_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpc', models.TextField(default='', help_text='Remote procedure call')),
                ('params', models.TextField(default='', help_text='Parameters to RPC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='_output',
            field=models.TextField(blank=True, default='', help_text='Leave blank. This will dispay the result of the command.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cmd_list',
            field=models.TextField(help_text='Comma separated list of command and parameters. e.g. ls,-la'),
        ),
        migrations.AlterField(
            model_name='job',
            name='signature',
            field=models.TextField(default='', help_text='Paste RSA PKCS#1 v1.5 signature of command. Ensure final input is base64 encoded.'),
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='key', to=settings.AUTH_USER_MODEL),
        ),
    ]
