# Generated by Django 3.1.5 on 2021-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rpc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpc',
            name='output',
            field=models.TextField(blank=True, default='', help_text='Leave blank. This will dispay the result of the rpc.'),
        ),
    ]
