# Generated by Django 3.1.5 on 2021-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210131_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpc',
            name='params',
            field=models.TextField(default='', help_text='Base64 encoded parameters for RPC function'),
        ),
    ]
