# Generated by Django 3.1.5 on 2021-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210131_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpc',
            name='signature',
            field=models.TextField(default='', help_text='Paste RSA PKCS#1 v1.5 signature of command. Ensure final input is base64 encoded.'),
        ),
    ]
