# Generated by Django 3.1.5 on 2021-01-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rpc_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpc',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
