# Generated by Django 3.1.5 on 2021-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210131_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpc',
            name='timestamp',
            field=models.DateTimeField(default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='rpc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
