# Generated by Django 3.1.5 on 2021-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210131_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpc',
            name='timestamp',
            field=models.DateTimeField(default='2020-01-01 00:00:00.000000UTC'),
        ),
    ]
