# Generated by Django 3.1.5 on 2021-01-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210131_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpc',
            name='timestamp',
        ),
    ]
